package com.kazimi.syarahweather.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors - Weather themed but Material 3 compliant
val md_theme_light_primary = Color(0xFF6B7B3A) // Natural green for primary
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF2F7E3)
val md_theme_light_onPrimaryContainer = Color(0xFF1F2607)
val md_theme_light_secondary = Color(0xFF5F6050)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE4E6D0)
val md_theme_light_onSecondaryContainer = Color(0xFF1C1E11)
val md_theme_light_tertiary = Color(0xFF3F676A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC2ECF0)
val md_theme_light_onTertiaryContainer = Color(0xFF002023)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCF5)
val md_theme_light_onBackground = Color(0xFF1B1C17)
val md_theme_light_surface = Color(0xFFFDFCF5)
val md_theme_light_onSurface = Color(0xFF1B1C17)
val md_theme_light_surfaceVariant = Color(0xFFE4E3D6)
val md_theme_light_onSurfaceVariant = Color(0xFF46473B)
val md_theme_light_outline = Color(0xFF77786A)
val md_theme_light_inverseOnSurface = Color(0xFFF2F1EA)
val md_theme_light_inverseSurface = Color(0xFF30312B)
val md_theme_light_inversePrimary = Color(0xFFD6DAC8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF6B7B3A)
val md_theme_light_outlineVariant = Color(0xFFC7C7BB)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors - Weather themed but Material 3 compliant
val md_theme_dark_primary = Color(0xFFD6DAC8)
val md_theme_dark_onPrimary = Color(0xFF343C18)
val md_theme_dark_primaryContainer = Color(0xFF4F5928)
val md_theme_dark_onPrimaryContainer = Color(0xFFF2F7E3)
val md_theme_dark_secondary = Color(0xFFC7CAB4)
val md_theme_dark_onSecondary = Color(0xFF313325)
val md_theme_dark_secondaryContainer = Color(0xFF47493A)
val md_theme_dark_onSecondaryContainer = Color(0xFFE4E6D0)
val md_theme_dark_tertiary = Color(0xFFA6D0D4)
val md_theme_dark_onTertiary = Color(0xFF083739)
val md_theme_dark_tertiaryContainer = Color(0xFF274E51)
val md_theme_dark_onTertiaryContainer = Color(0xFFC2ECF0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF13140F)
val md_theme_dark_onBackground = Color(0xFFE4E3DC)
val md_theme_dark_surface = Color(0xFF13140F)
val md_theme_dark_onSurface = Color(0xFFE4E3DC)
val md_theme_dark_surfaceVariant = Color(0xFF46473B)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C7BB)
val md_theme_dark_outline = Color(0xFF919084)
val md_theme_dark_inverseOnSurface = Color(0xFF13140F)
val md_theme_dark_inverseSurface = Color(0xFFE4E3DC)
val md_theme_dark_inversePrimary = Color(0xFF6B7B3A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFD6DAC8)
val md_theme_dark_outlineVariant = Color(0xFF46473B)
val md_theme_dark_scrim = Color(0xFF000000)

